version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: kanastra
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq

  celery:
    build: .
    command: celery -A debt_management worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - rabbitmq

  celery-beat:
    build: .
    command: celery -A debt_management beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - rabbitmq

volumes:
  postgres_data:
